export const SET_ALL_EXPERIENCE_DATA = 'SET_ALL_EXPERIENCE_DATA';
export const SET_POPULAR_EXPERIENCE_DATA = 'SET_POPULAR_EXPERIENCE_DATA';
export const SET_RECOMMENDED_EXPERIENCE_DATA = 'SET_RECOMMENDED_EXPERIENCE_DATA';